global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 3s
  repeat_interval: 1000ms
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:8081/dashboard/error'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
